// Generated by the Tensor Algebra Compiler (tensor-compiler.org)

num inner3_compute() {
  out_val = 0.0;

  for (int32_t iC = C1_pos[0]; iC < C1_pos[1]; iC++) {
    for (int32_t jC = C2_pos[iC]; jC < C2_pos[(iC + 1)]; jC++) {
      for (int32_t kC = C3_pos[jC]; kC < C3_pos[(jC + 1)]; kC++) {
        out_val += C_vals[kC] * C_vals[kC];
      }
    }
  }

  out_vals[0] = out_val;
  return out_val;
}
